version: "3.9"
services:
  db:
    image: mysql:5.7
    container_name: mysql_dc_api
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
     image: phpmyadmin
     container_name: phpmyadmin_dc_api
     restart: always
     depends_on:
       - db
     ports:
       - 8081:80
     environment:
       PMA_HOST: db
     networks:
       - dev

  www:
    build: docker
    container_name: php-apache-dc-api
    ports:
      - "8088:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
    dev:

volumes:
    db-data: